### ISSUE TITLE
Compatibility With New Arduino Uno R4 WiFi Board

### ISSUE THREAD

**Issue by woolseyj** [knolleary/pubsubclient#1016]
I have been enjoying using this library on an Arduino Uno WiFi Rev2 board.  Thank you.

However, while trying out this library on a newly purchased Arduino Uno R4 WiFi board, I am getting quite a few "error: 'strnlen' was not declared in this scope" errors from within the PubSubClient library and the IDE suggests using 'strlen' as an alternative.

Do you have any suggestions on how I can resolve this error?

Your help would be greatly appreciated.

**Comment by woolseyj** [comment]
FYI, I added an [issue](https://github.com/arduino/ArduinoCore-renesas/issues/18) to the ArduinoCore-renesas and an [issue](https://github.com/arduino/uno-r4-library-compatibility/issues/2) to the uno-r4-library-compatibility repositories.

**Comment by Willy9512** [comment]
I am having the exact same issue. Have you found a solution?

**Comment by woolseyj** [comment]
No, I am just using the Arduino Uno WiFi Rev2 board for now.

**Comment by tony2feathers** [comment]
I made a fork of PubSubClient which addresses these issues. I have tested it and have managed to get it to connect to my wifi and connect to the test.mosquitto.org mqtt broker. I am having problems with my local broker for some reason, and I'm unsure what the cause is, but the new forked library works as far as I can tell. https://github.com/tony2feathers/pubsubclient_UnoR4

**Comment by woolseyj** [comment]
The [issue](https://github.com/arduino/ArduinoCore-renesas/issues/18) was resolved in the ArduinoCore-renesas library.  The PubSubClient library is now working properly with the Arduino R4 WiFi board.
