### ISSUE TITLE
MQTT publish not working

### ISSUE THREAD

**Issue by ShaunodCIT** [knolleary/pubsubclient#161]
Hi there.

apologize if I happen to leave out any important details during this, I'm rather new to MQTT and the whole PubSub method

I made a game with my Arduino a few months back and I'm trying to incorporate MQTT into it so that I can publish messages to, let's say "Game/HighestScore" every time someone gets a new high score.

The code I used for this is taken from an example MQTT library I found, and I've run that library to confirm that it is in fact working.

Here is the code that I'm running:

    sprintf(msg, 50, "New High Score: %d", higestScoreNum);
    Serial.print("Publish message: ");
    Serial.print(msg);
    int i = client.publish(higestScoreTopic, msg);
    Serial.println(i);

The "int i = client.publish(higestScoreTopic, msg);" was put there to see if the method would return "1" to confirm that the publish happened, and it does.
This is what appears in my console:

    Publish message: New High Score: 3
    1

I have a serial terminal open that's subscribed to the "Game/HighestScore" topic, but it is nor receiving the published messages.

**Comment by Suxsem** [comment]
Can you provide a log of your mqtt broker?
Hi there.

apologize if I happen to leave out any important details during this, I'm rather new to MQTT and the whole PubSub method

I made a game with my Arduino a few months back and I'm trying to incorporate MQTT into it so that I can publish messages to, let's say "Game/HighestScore" every time someone gets a new high score.

The code I used for this is taken from an example MQTT library I found, and I've run that library to confirm that it is in fact working.

Here is the code that I'm running:

    sprintf(msg, 50, "New High Score: %d", higestScoreNum);
    Serial.print("Publish message: ");
    Serial.print(msg);
    int i = client.publish(higestScoreTopic, msg);
    Serial.println(i);

The "int i = client.publish(higestScoreTopic, msg);" was put there to see if the method would return "1" to confirm that the publish happened, and it does.
This is what appears in my console:

    Publish message: New High Score: 3
    1

I have a serial terminal open that's subscribed to the "Game/HighestScore" topic, but it is nor receiving the published messages.

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/knolleary/pubsubclient/issues/161

**Comment by ShaunodCIT** [comment]
@Suxsem I'm not sure how to obtain that.

**Comment by Suxsem** [comment]
What is your mqtt broker? Mosquitto? Or are you using a cloud broker?
@Suxsem I'm not sure how to obtain that.

---

**Comment by ShaunodCIT** [comment]
@Suxsem I'm using mosquitto.

**Comment by Suxsem** [comment]
Great. So just launch it with the -v param (verbose) and paste here the output when you try to publish from your arduino
@Suxsem I'm using mosquitto.

---

**Comment by ShaunodCIT** [comment]
@Suxsem adding the -v param didn't change anything, there was still no output to the subscriber.

**Comment by Suxsem** [comment]
The log output doesn't go to the subscriber. You just launch the broker with the -v param and watch the log inside the terminal
@Suxsem adding the -v param didn't change anything, there was still no output to the subscriber.

---

**Comment by ShaunodCIT** [comment]
@Suxsem Sorry, I miss read that. I just did that and the server didn't say it received the publish.

**Comment by ShaunodCIT** [comment]
@Suxsem ummmm, never mind. It's kinda just working now... I changed absolutely nothing, and it's just kinda working now...

**Comment by edwin-oetelaar** [comment]
please close issue, since it was user error all along.
