### ISSUE TITLE
Question about callback

### ISSUE THREAD

**Issue by hellzakk** [knolleary/pubsubclient#172]
Hi @knolleary this is just a question, i have understand how the "normal" callback functions work but i dont understand when the callback function in the mqtt_publish_in_callback.ino example is called... every client.loop() i suppose...
Can you give a hint?

**Comment by knolleary** [comment]
The callback is invoked whenever a new message arrives due to the subscription the client has made.

As this is a single threaded environment, each time you call `client.loop()` that allows the client to check for any incoming MQTT packets and to process them appropriately. In the case of an incoming MQTT Publish message, the processing will involve calling the callback with the received message.

The `mqtt_publish_in_callback` example is there to show how you can publish a message in response to receiving one. Due to the internal buffer of the client being used for both incoming and outgoing messages, the example shows how you should take a copy of the payload so it doesn't get overwritten.
