### ISSUE TITLE
Conceptual question (not an issue to be addressed)

### ISSUE THREAD

**Issue by marcelops** [knolleary/pubsubclient#245]
My project collects GPS data and stores it in a SD card.  This file eventually needs to be consolidated to a server.

Considere the following objects in this project:  [Arduino] + [ESP8266 module] + [SD Card]

Pretend there is a text-file in the SD card containing 100,000 lines (or about 2Mb worth of data).  (Q1) Would it be a good practice to parse the entire file through a MQTT message using PubSubClient?  If the answer to this is “yes”, then (Q2) how can I be 100% sure that the message was properly delivered to the MQTT server?

(Q3) Is there a function in PubSubClient to parse files, or do I need to construct a char[] with the content of the file?

If none of this make sense, then (Q4) would transferring the file via HTTP Post make more sense?

Thanks,
Marcelo

**Comment by knolleary** [comment]
Hi @marcelops 

you will be constrained by the available memory on the ESP8266. You won't have the space to load 2Mb of data in to memory in order to create the necessary MQTT packet.

An alternative approach would be chop it up into smaller pieces and send them individually. You'd need to add some meta data so the receiving end would be able to reassemble the pieces.

You could publish a message back to the client to confirm full receipt of the data.

This library is only concerned with the MQTT protocol - where you get the data is your concern.

As for alternatives, I'd ask that on the relevant arduino/esp8266 forums for guidance. It isn't something I use the client for, so I'm not in a position to advise.
