### ISSUE TITLE
Cross Connection issues

### ISSUE THREAD

**Issue by InvisiBug** [knolleary/pubsubclient#289]
Im having an issue when I get two nodes to subscribe to each other. I’m running mosquito on a raspberry pi. If I have one node publishing all of its data and another subscribed it works fine, but if I have both nodes publishing and both subscribed to the other the network crashes. One node resets and reconnects, which causes the other to reset… and so on. Does anyone know what’s happening? I can post my code but it’s massive. I’m hosting a javascript controlled bootstrap website :)

**Comment by knolleary** [comment]
Hi,

I assume your 'nodes' are using this library? Please don't post code.

Some things to check for:

 - each node must use a unique client id (the string you pass in the connect function). The fact you say you have a node publishing and a node subscribing successfully suggests you have this setup correctly
 - if they are both publishing and subscribing to each other, make sure you aren't generating message loops - where a single publish bounces endlessly between the two nodes.
 - ensure you are calling `client.loop` regularly on both clients so that the network can be regularly serviced - but don't call it so often that it overloads the hardware.
