### ISSUE TITLE
max payload length

### ISSUE THREAD

**Issue by fabian727** [knolleary/pubsubclient#356]
Hello @ all,

thanks for this great library. After fixing own foolish default errors, I got your library running.
My problem: I want to stream 128 Byte in 1 Mqtt-Frame.
Your library sets this to the maximum. If my publisher sends more than 100 Bytes the callback-routine won't be called and executed.

My questions:
1. why is it alltogether limited? ( i know my space is not endless, but isn't this my problem?)
2. why do I have troubles at 100 bytes payload and not the defined 128 bytes?

Thanks in advance.
Fabian

p.s.:
my source code is [here](https://github.com/fabian727/AmbiMqttNodeMcu/blob/master/slave/mqtt_rgb_client/mqtt_rgb_client.ino)
A directory above is the same script written in lua, working with mqtt and a payload = 128 bytes

**Comment by knolleary** [comment]
It is limited because the library reserves an internal buffer in memory that can contain the packet. 
If your device has sufficient memory, you can modify the max size (as described in the docs) in `PubSubClient.h`.

The value is the max MQTT packet length - not the max payload size. The MQTT Publish packet includes both the payload and topic, along with some additional header bytes. So you need to take into account the length of the topic.

**Comment by fabian727** [comment]
thanks for your quick reply and sorry for not reading enough (your documentary)
