### ISSUE TITLE
Using ESP32 as a publisher , PubSub timesout/doesnt publish after about 20 seconds of inactivity?

### ISSUE THREAD

**Issue by acbrandao** [knolleary/pubsubclient#399]
I'm making a basic door sensor using ESP32 (Wemos) attached to a MQTT (Mosquitto) running on raspberry pi. Everything is working as expected ,when the door opens a message is sent with the door state, then when the door closes another message with the new state. Except for when the door (sensor) stays open for longer than 20s , for some reason it doesn't issue the SendMQTT_message (code here) 
https://github.com/acbrandao/arduino_projects/blob/master/esp32_mqtt_door/esp32_mqtt_door.ino
issue is around line line#260.

The issue is if the signal is sent after 20seocnds, nothing happens, I can see the code being executed on the Serial monitor of the ESP32 but no message appears to be received on MQTT broker.. strange, I checked and set the KEEPALIVE to 45 secs from PUbSub , but no effect, is there another setting?

**Comment by knolleary** [comment]
Hi, the problem is in this loop: 
https://github.com/acbrandao/arduino_projects/blob/aa1c83fffcc20f5514dbd1f81f9b3fd3ae760360/esp32_mqtt_door/esp32_mqtt_door.ino#L239-L249

You need to add a call to `client.loop()` in there so the MQTT client is able to process its keepalive handling. If that loop blocks and prevents client.loop from being called, the client will timeout the connection.

**Comment by acbrandao** [comment]
Thanks I'll give that a try, that should resolve the issue, but I'm confused shouldn't the MAX_KEEPALIVE #define supersede the need to put a polling loop construct ?, please forgive my ignorance.  If that's not the case than what role does the #define MAX_KEEPALIVE 15 serve?

**Comment by knolleary** [comment]
If you're using the arduino IDE to build the sketch, you cannot redefined MQTT_KEEPALIVE in your own script - you have to edit it in PubSubClient.h.
