### ISSUE TITLE
Receiving Previous message payload in current message payload

### ISSUE THREAD

**Issue by wahibmichael** [knolleary/pubsubclient#737]
I'm using the below to convert the payload to string
 String StateID((char *)payload); 
my issue is that I receive part of the previous payload in the new message payload if the new message is shorter than the previous one.
is there a way to flush the memory buffer of payload?

**Comment by knolleary** [comment]
This is because you are ignoring the length parameter that is passed to the callback. This tells you how long the payload is. Anything beyond that will be old data.

If you want to treat the payload as a string, you need to make sure it is 0-terminated. Something like:

```
payload[length] = 0;
```

That will ensure that when you pass it to the String constructor, it only reads the valid data.
