### ISSUE TITLE
while{} loop of death

### ISSUE THREAD

**Issue by macedolfm** [knolleary/pubsubclient#87]
If the Client loses connection or for some reason can not provide an available() == true you will stay stuck here forever....

uint8_t PubSubClient::readByte() {
    while(!_client->available()) {}  <<<<<<<<<< loop of death !!!! 
    return _client->read();
}

Virtual Client.h read() implementation returns an INT not a uint8_t. A overloaded Client returning "-1" means the requested read() failed for any reason and should be treated like invalid. Current PubSubClient::readPacket() approach is way too optimistic.

**Comment by vicatcu** [comment]
@macedolfm @knolleary et al I'm working on a fix for this in [my fork](https://github.com/vicatcu/pubsubclient). I think what's pushed right now is basically ready for a pull request actually if you guys want to review it / help test it. 

I tried to implement it the fix in such a way that it is non-interfering with the current implementation. I basically added a public method to set the read timeout in milliseconds.The newly added code only comes into play if one first calls setReadTimout from the sketch, and I initialized it to -1 in all the constructors (which disables the newly added code). If we prefer the default behavior to change to timeout instead of infinite loop, we just need to come up with an agreed upon sensible default for how long the timeout should be. 

The actual timeout code is modeled after the venerable Arduino blinkWithoutDelay example (so it should handle timer roll-over gracefully).

**Comment by macedolfm** [comment]
Great !!! And what about returning -1 on timeout? Using uint8_t implies -1 (timeout or error) will never happen...

**Comment by vicatcu** [comment]
@macedolfm What would be the point of doing that? readByte is a private method, maybe I'm misunderstanding you... personally I'm more concerned about whether I'm doing the "right" thing in readPacket by returning zero on a timeout detection.

**Comment by vicatcu** [comment]
Note (!value) will evaluate to "true" if and only if value equals zero.

**Comment by macedolfm** [comment]
@vicateu, well, returning -1 will allow the readByte() loop inside public readPacket() to properly abort instead of keep calling a dead _client over and over in hope of getting a end of packet (digit & 128) that will never happen because the timeout/broken client is always returning a foo 0 pretending this is a valid _client.read value...am I missing something?

**Comment by macedolfm** [comment]
@vicateu, I am using your PubSub with ESP8266 and already experienced a locked module twice with the unpatched class, I am using both corrections on my patched version, the timeout and the -1 and having readPacket() returning 0 on a broke _client & readByte() and so far, so good...

**Comment by vicatcu** [comment]
@macedolfm didn't get notifications on your comments (you got my handle slightly wrong).  Note that in order to "activate" my code at all you need to call, e.g., mqttClient.setReadTimeout(100), in setup of your sketch (otherwise it will act the same as it ever did with the infinite loop). Also, I'm still not understanding what you're trying to describe to me regarding using -1 somewhere.

**Comment by macedolfm** [comment]
@vicatcu Hi, my point in returning -1 on _client.readByte() is to signal the calling function that the returning data is invalid for some reason (timeout, _client hang/crash, lost connection, etc.) since 0 is a valid readByte() data, if we do not return -1 on erro there is no way the calling function will be aware of the error condition at readByte(), beig so, it will keep calling readByte() as no error had ever happened. In the PubSub case, since we are returning 0 on error/timeout, the readPacket() may also get stuck in a infinite looping while waiting for an end of packet flag ie. readByte() == (digit & 128), again a deadlock... As far as I know the virtual _client::readByte() returns INT for this very same reason, in ESP8266 core the Serial, Ethernet & WiFi should return -1 on read() error, why then PubSub is turning the -1 INT and retuning 0 BYTE on error ?

**Comment by knolleary** [comment]
Hi, @vicatcu , thanks for looking at this, my apologies it has taken a bit of time for me to look at this properly.

I think the logic is basically sound with your approach. One comment for you:  as the read timeout isn't a parameter that a user would need to change dynamically, it would be more consistent with other such config options to handle it as a #define in the header - `MQTT_SOCKET_TIMEOUT` ?. I would suggest something like 15 seconds - which happens to also be the default keepalive timeout at the protocol level. As with `MQTT_KEEPALIVE`, it should be specified in seconds in the header. This approach also removes the need for the setReadTimeout function.

May be worth considering changing this line to timeout with MQTT_SOCKET_TIMEOUT rather than MQTT_KEEPALIVE as it does today: https://github.com/vicatcu/pubsubclient/blob/master/src/PubSubClient.cpp#L194 

@macedolfm the calling function `readPacket` will return 0 in the case of an invalid packet which will cause the packet to be ignored. I'd rather keep the logic around that as it is - if there is an underlying connection issue, it will be discovered and handled without causing it to spin.

**Comment by vicatcu** [comment]
@macedolfm I fundamentally changed the signature of readByte... It now returns a boolean; true if it succeeds in reading a byte or false if it does not. If it succeeds it writes the actually byte that was read into the memory location passed into the function as an argument (as a pointer).

**Comment by vicatcu** [comment]
@knolleary sure sounds good, I'll make the changes, retest, push an update and report back.

**Comment by vicatcu** [comment]
@knolleary it's subtle, but incidentally I think that the RHS of that comparison you linked to in connect() ought to be cast to int32_t as well (to handle millis roll-over as is done in blinkWithoutDelay), so I'll make that change as well while I'm at it, ok?

**Comment by vicatcu** [comment]
@knolleary I've pushed an update to [my fork](https://github.com/vicatcu/pubsubclient) based on your comments if you want to preview/review. Letting the code run for a while now to test resilience.

**Comment by macedolfm** [comment]
@vicatcu , I´ve reviewed the code and it looks OK, will put it to the test. It is pretty much the same I patched on my running pubsubclient-2.3 version, except that I still rather (for sintax compliance with Stream class) have the -1 being returned on failure, also set the TIMEOUT as a  #defined like all other "// Possible values for client.state()" in PubSubClient.h, but result is the same anyway....thank a lot for the patience !! Cheers.

Arduino Reference: https://www.arduino.cc/en/Reference/StreamRead

**Comment by knolleary** [comment]
@macedolfm as it is an entirely internal api, I'm not too worried about it, but once we get the main fix sorted and merged, I'll have another look at it.

Thanks to you both for your contributions on this.

**Comment by knolleary** [comment]
Closed by #93
