### ISSUE TITLE
MQTT + HTTP

### ISSUE THREAD

**Issue by dataino-it** [knolleary/pubsubclient#92]
Hello

I am using your product successfully in my project www.dataino.it.
I now I have, however, as well as connect with my server MQTT I do HTTP calls to a device.

while the channel with MQTT works receives and transmits the HTTP call fails

is an impossible thing to do? or do I close MQTT before opening the HTTP channel?

any suggestions ?
[test-mqtt-http.txt](https://github.com/knolleary/pubsubclient/files/37508/test-mqtt-http.txt)

**Comment by knolleary** [comment]
Not all hardware supports having multiple connections open at the same time. That would be the first thing I'd check.

Otherwise, it is a question of how the http request fails. Can you use a network sniffer (eg wireshark) to see if there's any network activity around the request? Have you verified the http code works standalone (without the mqtt client connected)?

As this isn't a bug with the mqtt client, I'm going to close the issue, but feel free to add comments if you want any more pointers.

**Comment by dataino-it** [comment]
Both HTTP client and MQTT work perfectly separate. 

Now in fact I was trying to put them together
tonight analyze network traffic to understand what happens thanks for
the advice. 

Il 18.11.2015 08:56 knolleary ha scritto: 

> Not all hardware supports having multiple connections open at the same time. That would be the first thing I'd check. 
> 
> Otherwise, it is a question of how the http request fails. Can you use a network sniffer (eg wireshark) to see if there's any network activity around the request? Have you verified the http code works standalone (without the mqtt client connected)? 
> 
> As this isn't a bug with the mqtt client, I'm going to close the issue, but feel free to add comments if you want any more pointers. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

  

Links:
------
[1]
https://github.com/knolleary/pubsubclient/issues/92#issuecomment-157637996
